[theme]
base="dark"
#primaryColor="purple"
primaryColor="#FF4B4B"
#backgroundColor="#000033"
#secondaryBackgroundColor="#F0F2F6"
textColor="#FFF"
font="sans serif"
[client]
showSidebarNavigation = false
